import type { Metadata } from "next";
import { Anton } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Script from "next/script";
import Image from "next/image";

const inter = Anton({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Playlist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="absolute inset-0 z-0">
          <Image
            src="/static.png"
            alt="background"
            width={100}
            height={100}
            className="h-screen w-full"
          />
        </div>
        <div className="z-10 relative">{children}</div>
        <Script
          src="https://js-cdn.music.apple.com/musickit/v1/musickit.js"
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
